### ISSUE TITLE
サーバーを作る

### ISSUE THREAD

**Issue by nabe1005** [codeforkosen/Kakomimasu#1]
# サーバーを作ろう

[決めたプロトコル](https://hackmd.io/IDgCfeQ8SqWQuK9PzkG8xQ)をもとにサーバーを立てる

## 決めたい

- どの言語で作るか(Node.jsならExpressとか？)

**Comment by taisukef** [comment]
Deno/JavaScriptでつくると簡単だよー
https://fukuno.jig.jp/2876

**Comment by taisukef** [comment]
できた！
https://github.com/codeforkosen/Kakomimasu/tree/master/apiserver
