### ISSUE TITLE
パスワードがusers.jsonに保存されない

### ISSUE THREAD

**Issue by ninja03** [codeforkosen/Kakomimasu#13]
https://github.com/codeforkosen/Kakomimasu/blob/a96da1c85e61bac0ba2c95c4319605f91274eec9/apiserver/user.ts#L42
stringifyで呼ばれるtoJSONにpasswordがないので

**Comment by taisukef** [comment]
https://github.com/codeforkosen/Kakomimasu/pull/14
解決！

**Comment by ninja03** [comment]
ありがとうございます
