### ISSUE TITLE
アクセスした順にマッチするのはどうなんだろう？

### ISSUE THREAD

**Issue by kamekyame** [codeforkosen/Kakomimasu#39]
ゲームロビーの実装方法
・練習用と本番用

**Comment by kamekyame** [comment]
https://cdn.tactosh.com/quiz/

｢みんなで早押しクイズ｣
みたいな感じにするといいのかも？

- ランダムマッチ
　　　　- 現方式のやつ。入ってきた順
- フリーマッチ
　　　　- フィールドの設定(点数、エージェント数、ターン数、ターン時間など)ができる(Jsonおくる？) 
　　　　- ユーザ招待
　　　　- などなど

**Comment by taisukef** [comment]
ランダムマッチ（現行方式）

フリーマッチ
- ゲーム作成（ボード設定、プリセット選ぶ or ファイルアップロード）
  - 非公開ゲーム（URLを特定の人に送る、大会に必須、優先！）
 - 公開ゲーム（ゲーム参加で入れる）
- ゲーム参加（ゲーム参加用URLから）
