### ISSUE TITLE
フロントデザイン案募集

### ISSUE THREAD

**Issue by kamekyame** [codeforkosen/Kakomimasu#46]

**Comment by taisukef** [comment]
何のデザイン？

**Comment by kamekyame** [comment]
ブラウザ表示部分のです！
今のままだとゲーム一覧のtableの部分とかがおしゃれじゃないなぁと思ってまして...

**Comment by taisukef** [comment]
なるほど、いい感じにしたいねっ

**Comment by kamekyame** [comment]
ReactとMaterial-UIを使ってみました！
ボタンやフォームなどのデザインがモダンな感じで統一されました。
#173
