### ISSUE TITLE
Kakomimasu core 内、できればsetIntervalを使いたくない

### ISSUE THREAD

**Issue by taisukef** [codeforkosen/Kakomimasu#54]
coreを他の言語への移植がしやすいように

**Comment by kamekyame** [comment]
具体的にはどんな感じにするといいでしょう？

kakomimasu.jsでsetIntervalするんじゃなくて、apiserver.tsの方でした方がいいのでしょうか…
それとも別の方法みたいなのがあるのでしょうか…

**Comment by taisukef** [comment]
apiserver.ts 側でsetIntervalで待ってくれ方がいいね
ポーリングするか、コールバックするか、コアを使ってどう実装するかは利用側で決められるようにした方が使い勝手アップ
